{% set name = "watermark" %}
{% set version = "2.0.0" %}
{% set sha256 = "4cab56ddf215bf83a7133ce9e3ac073a0ecbd61316efa4422d09829d0b906c8b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - ipython

  run:
    - python
    - ipython
    - certifi

test:
  imports:
    - watermark
    - certifi

about:
  home: https://github.com/rasbt/watermark
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'IPython magic function to print date/time stamps and various system information.'
  dev_url: https://github.com/rasbt/watermark

extra:
  recipe-maintainers:
    - proinsias
