travis:
  secure:
    BINSTAR_TOKEN: kDn49BTSV+qfs/WZsvq94QImRxpIbRFbi6CXpW1ddqYwnFnCZEYQSwrKszgplQm5b/PqP0xjAwd1LNEX/4JaVKrWx6/Wo3yl+uAbP3+7viMrzYX9QRH0gFbJShDtLVnV1SoI05t3TjY/46oY2/JCkumJ8+UUDuDGfQQtGJ0xWu2vHevfixIjaUGR5fuz9hUXB3PSYk4eaCUQV817yWGjK2xnTZA8NZ9UQ1dY90bamJDGyskKZwubvTg3fgX5ponQJaPbG5+H5LWf0za3KZkr8IBknf7cV3oq+a8fRnA6Mj/DNAFDKELVOcrkCelayka0evCEaFYHG4teycPKs3h8aODgMle2+ETi1p6K8ZMjkEHhbMZ22A0UJGcfmJPWHG1J7WLf8tOSVe7q0Wnk/Y3ZagjCEFt2YLVfQSuAViVAvvNW2pIeoNQgHx3diInv3OKNVu62eVUW+u0MQnKJRID+1MpZlc6q8VNAOb5R7dvixtXtvrBpKUokoV6+4qOf5Ka3N7L6TQmHAHinmkkSxOCSRHuK8RJ5ndeeW835RDwQ0YEvbeqtXiePhvuU5Z0EkK/AIqhtqWTthqtlBYGiP1MqEABBvkvevMZVQUewYfa8yfsWXBYPL41tTpSiRtER3vYcaViaGYk5gffHExnkN4J2tJhi083yLWJG3Fz+mH8rT1o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
